### ISSUE TITLE
Will requiring Rust Nightly be necessary?

### ISSUE THREAD

**Issue by soundprojects** [PaulWagener/leptos_animation#3]
Hi

appreciate your library, I was wondering if in the near future you expect that requiring Rust Nightly will be necessary or if there are any plans to support Rust Stable.

Thanks

**Comment by PaulWagener** [comment]
Nope, shouldn't be necessary. I've [removed](https://github.com/PaulWagener/leptos_animation/commit/1e18c151674a4d6f1344a72bc5b60ec978c6d364) it from the requirements which is in version 0.5.2
